"""add is_revoked to sessions

Revision ID: 3607ef61f2ea
Revises: 874e24a3ab31
Create Date: 2026-05-26 12:34:31.238045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3607ef61f2ea'
down_revision: Union[str, Sequence[str], None] = '874e24a3ab31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_revoked')
    # ### end Alembic commands ###
